/* 
 * File:   BCBP_ItemIDs.h
 * Author: johny
 *
 * Created on October 18, 2015, 2:28 PM
 */

#ifndef BCBP_ITEMIDS_H
#define	BCBP_ITEMIDS_H

/*
#define FORMAT_CODE_ID 1
#define NUMBER_OF_LEGS_ENCODED_ID 5
#define PASSENGER_NAME_ID 11
#define ELECTRONIC_TICKET_INDICATOR_ID 253
#define OPERATING_CARRIER_PNR_CODE_ID 7
#define FROM_CITY_AIRPORT_CODE_ID 26
#define TO_CITY_AIRPORT_CODE_ID 38
#define OPERATING_CARRIER_DESIGNATOR_ID 42
#define FLIGHT_NUMBER_ID 43
#define DATE_OF_FLIGHT_JULIAN_DATE_ID 46
#define COMPARTMENT_CODE_ID 71
#define SEAT_NUMBER_ID 104
#define CHECKIN_SEQUENCE_NUMBER_ID 107
#define PASSENGER_STATUS_ID 113
#define FIELD_SIZE_OF_FOLLOWING_VARIABLE_SIZE_FIELD_ID 6
#define BEGINNING_OF_VERSION_NUMBER_ID 8
#define VERSION_NUMBER_ID 9
#define FIELD_SIZE_OF_FOLLOWING_STRUCTURED_MESSAGE_UNIQUE_ID 10
#define PASSENGER_DESCRIPTION_ID 15
#define SOURCE_OF_CHECKIN_ID 12
#define SOURCE_OF_BOARDING_PASS_ISSUANCE_ID 14
#define DATE_OF_ISSUE_OF_BOARDING_PASS_JULIAN_DATE_ID 22
#define DOCUMENT_TYPE_ID 16
#define AIRLINE_DESIGNATOR_OF_BOARDING_PASS_ISSUER_ID 21
#define BAGGAGE_TAG_LICENCE_PLATE_NUMBER_S_ID 23
#define FIELD_SIZE_OF_FOLLOWING_STRUCTURED_MESSAGE_REPEATED_ID 17
#define AIRLINE_NUMERIC_CODE_ID 142
#define DOCUMENT_FORM_SERIAL_NUMBER_ID 143
#define SELECTEE_INDICATOR_ID 18
#define INTERNATIONAL_DOCUMENTATION_VERIFICATION_ID 108
#define MARKETING_CARRIER_DESIGNATOR_ID 19
#define FREQUENT_FLYER_AIRLINE_DESIGNATOR_ID 20
#define FREQUENT_FLYER_NUMBER_ID 236
#define ID_AD_INDICATOR_ID 89
#define FREE_BAGGAGE_ALLOWANCE_ID 118
#define FOR_INDIVIDUAL_AIRLINE_USE_ID 4
#define BEGINNING_OF_SECURITY_DATA_ID 25
#define TYPE_OF_SECURITY_DATA_ID 28
#define LENGTH_OF_SECURITY_DATA_ID 29
#define SECURITY_DATA_ID 30
*/


namespace bcbp{
    
const int FORMAT_CODE_ID(1);
const int NUMBER_OF_LEGS_ENCODED_ID(5);
const int PASSENGER_NAME_ID(11);
const int ELECTRONIC_TICKET_INDICATOR_ID(253);
const int OPERATING_CARRIER_PNR_CODE_ID(7);
const int FROM_CITY_AIRPORT_CODE_ID(26);
const int TO_CITY_AIRPORT_CODE_ID(38);
const int OPERATING_CARRIER_DESIGNATOR_ID(42);
const int FLIGHT_NUMBER_ID(43);
const int DATE_OF_FLIGHT_JULIAN_DATE_ID(46);
const int COMPARTMENT_CODE_ID(71);
const int SEAT_NUMBER_ID(104);
const int CHECKIN_SEQUENCE_NUMBER_ID(107);
const int PASSENGER_STATUS_ID(113);
const int FIELD_SIZE_OF_FOLLOWING_VARIABLE_SIZE_FIELD_ID(6);
const int BEGINNING_OF_VERSION_NUMBER_ID(8);
const int VERSION_NUMBER_ID(9);
const int FIELD_SIZE_OF_FOLLOWING_STRUCTURED_MESSAGE_UNIQUE_ID(10);
const int PASSENGER_DESCRIPTION_ID(15);
const int SOURCE_OF_CHECKIN_ID(12);
const int SOURCE_OF_BOARDING_PASS_ISSUANCE_ID(14);
const int DATE_OF_ISSUE_OF_BOARDING_PASS_JULIAN_DATE_ID(22);
const int DOCUMENT_TYPE_ID(16);
const int AIRLINE_DESIGNATOR_OF_BOARDING_PASS_ISSUER_ID(21);
const int BAGGAGE_TAG_LICENCE_PLATE_NUMBER_S_ID(23);
const int FIELD_SIZE_OF_FOLLOWING_STRUCTURED_MESSAGE_REPEATED_ID(17);
const int AIRLINE_NUMERIC_CODE_ID(142);
const int DOCUMENT_FORM_SERIAL_NUMBER_ID(143);
const int SELECTEE_INDICATOR_ID(18);
const int INTERNATIONAL_DOCUMENTATION_VERIFICATION_ID(108);
const int MARKETING_CARRIER_DESIGNATOR_ID(19);
const int FREQUENT_FLYER_AIRLINE_DESIGNATOR_ID(20);
const int FREQUENT_FLYER_NUMBER_ID(236);
const int ID_AD_INDICATOR_ID(89);
const int FREE_BAGGAGE_ALLOWANCE_ID(118);
const int FOR_INDIVIDUAL_AIRLINE_USE_ID(4);
const int BEGINNING_OF_SECURITY_DATA_ID(25);
const int TYPE_OF_SECURITY_DATA_ID(28);
const int LENGTH_OF_SECURITY_DATA_ID(29);
const int SECURITY_DATA_ID(30);

}



#endif	/* BCBP_ITEMIDS_H */

